#tmp_src
services:
  nginx:
    container_name: tmp_name
    image: nginx:latest
    ports:
      - "tmp_port:80"
    restart: unless-stopped
    networks:
      anett:
        ipv4_address: tmp_ip
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - tmp_src:/usr/share/nginx

networks:
  anett:
    external: true
