#tmp_src
services:
  ftp:
    container_name: tmp_name
    image: metabrainz/docker-anon-ftp
    ports:
      - "tmp_port:21"
      - 65500-65515:65500-65515
    networks:
      anett:
        ipv4_address: tmp_ip
    restart: unless-stopped
    environment:
      - ANON_ROOT=tmp_src
    volumes:
      - tmp_src:tmp_src:ro

networks:
  anett:
    external: true
